### ISSUE TITLE
Make pride reinit less chatty

### ISSUE THREAD

**Issue by gnagy** [prezi/pride#157] opened 2015-07-22 08:08 UTC
Right now the output looks like this. Dropping the gradle deamon info would reduce clutter a lot.
...
47/47] Initializing module something-something
Tooling API is using target Gradle version: 2.4.
Connected to daemon DaemonInfo{pid=46483, address=[d09ffba7-166a-4c7d-a37d-c84bc862dd6d port:55380, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=a8d25f12-c3aa-4d3f-85a6-2d04f2f404ae,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home,daemonRegistryDir=/Users/greg/.gradle/daemon,pid=46483,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=c4eaad58-ecf2-4da4-bdb3-5e3f8d7b03b5.1, currentDir=/Users/greg/Dev/prides/all}.
Received result Success[value=org.gradle.tooling.internal.provider.BuildActionResult@256f88d] from daemon DaemonInfo{pid=46483, address=[d09ffba7-166a-4c7d-a37d-c84bc862dd6d port:55380, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=a8d25f12-c3aa-4d3f-85a6-2d04f2f404ae,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home,daemonRegistryDir=/Users/greg/.gradle/daemon,pid=46483,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}.

**Comment by lptr** [comment] 2015-07-23 13:30
Duplicate of #2.

**Closed by lptr** 2015-07-23 13:30 UTC
